---
version: '3.8'
services:
    zookeeper:
        image: bitnami/zookeeper:latest
        container_name: zookeeper
        ports:
            - 2181:2181
        environment:
            ALLOW_ANONYMOUS_LOGIN: yes
        networks:
            - kafka_network

    kafka:
        image: bitnami/kafka:latest
        container_name: kafka
        ports:
            - 9092:9092
        environment:
            KAFKA_LISTENERS: INSIDE://0.0.0.0:9091,OUTSIDE://0.0.0.0:9092
            KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9091,OUTSIDE://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_BROKER_ID: 1
        depends_on:
            - zookeeper
        networks:
            - kafka_network

    kafka-ui:
        image: provectuslabs/kafka-ui:latest
        container_name: kafka-ui
        ports:
            - 9100:8080
        environment:
            KAFKA_CLUSTERS_0_NAME: local
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9091
            KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
        depends_on:
            - kafka
        networks:
            - kafka_network

networks:
    kafka_network:
        driver: bridge

volumes:
    docker_auth:
